config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get "terms_of_use", to: "static_pages#terms_of_use"
  get "privacy_policy", to: "static_pages#privacy_policy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :posts, only: %i[index show edit update destroy] do
  end
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show edit update destroy]
    collection do
      get 'map', to: 'shops#map', as: 'map'
      get :auto_search
    end
    collection do
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]
  resources :likes, only: %i[index create destroy]

  resource :user, only: [:show]

  get 'images/ogp_image.png', to: 'images#ogp', as: 'images_ogp'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :set_google_maps_api_key

  def top
    @q = Shop.ransack(params[:q])
    @shops = Shop.all
    gon.shops = @shops.as_json
  end

  private

  def set_google_maps_api_key
    gon.google_maps_api_key = Rails.application.credentials.GOOGLE_MAPS_API_KEY
  end

end

app/views/static_pages/privacy_policy.html.erb
<% content_for(:title, t('.title')) %>
<div class="md:mx-32 mt-4 mb-12 flex items-center justify-center">

  <div class="rounded bg-white p-7 md:p-10 dark:bg-base-200">
    <h1 class="mb-4 text-base md:text-2xl font-bold dark:text-neutral"><%= t('.title') %></h1>
    <p class="mb-6 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">Learn&Latte（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">お客様から取得する情報</h2>
      <p class="mb-2 text-xs md:text-sm text-gray-700 dark:text-neutral">当社は、お客様から以下の情報を取得します。</p>
      <ul class="pl-8 list-disc text-xs md:text-sm leading-8 text-gray-700 dark:text-neutral">
        <li>氏名(ニックネームやペンネームも含む)</li>
        <li>メールアドレス</li>
        <li>写真や動画</li>
        <li>外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
        <li>Cookie(クッキー)を用いて生成された識別情報</li>
        <li>当社ウェブサイトの滞在時間、入力履歴、購買履歴等の当社ウェブサイトにおけるお客様の行動履歴</li>
        <li>当社アプリの起動時間、入力履歴、購買履歴等の当社アプリの利用履歴</li>
      </ul>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">お客様の情報を利用する目的</h2>
      <p class="mb-2 text-xs md:text-sm text-gray-700 dark:text-neutral">当社は、お客様から取得した情報を、以下の目的のために利用します。</p>
      <ul class="pl-8 list-disc text-xs md:text-sm leading-8 text-gray-700 dark:text-neutral">
        <li>当社サービスに関する登録の受付、お客様の本人確認、認証のため</li>
        <li>お客様の当社サービスの利用履歴を管理するため</li>
        <li>当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため</li>
        <li>当社のサービスに関するご案内をするため</li>
        <li>お客様からのお問い合わせに対応するため</li>
        <li>当社の規約や法令に違反する行為に対応するため</li>
        <li>当社サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
        <li>当社規約の変更等を通知するため</li>
        <li>以上の他、当社サービスの提供、維持、保護及び改善のため</li>
      </ul>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">安全管理のために講じた措置</h2>
      <p class="mb-2 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">第三者提供</h2>
      <p class="text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
      <p class="mb-2 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">但し、次の場合は除きます。</p>
      <ul class="pl-8 list-disc text-xs md:text-sm leading-8 text-gray-700 dark:text-neutral">
        <li>個人データの取扱いを外部に委託する場合</li>
        <li>当社や当社サービスが買収された場合</li>
        <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
        <li>その他、法律によって合法的に第三者提供が許されている場合</li>
      </ul>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">アクセス解析ツール</h2>
      <p class="mb-2 text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。</p>
      <%= link_to "Googleアナリティクス利用規約（外部サイト）", "https://marketingplatform.google.com/about/analytics/terms/jp/", target: "_blank", class: "link link-primary text-xs md:text-sm dark:link-secondary" %>
    </div>

    <div class="mb-6">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">プライバシーポリシーの変更</h2>
      <p class="text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">当社は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
    </div>

    <div class="mb-8">
      <h2 class="mb-2 text-base md:text-lg font-bold dark:text-neutral">お問い合わせ</h2>
      <p class="text-xs md:text-sm leading-7 text-gray-700 dark:text-neutral">お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、<%= link_to "お問い合わせフォーム", 'https://docs.google.com/forms/d/e/1FAIpQLScEoalxTjFE971Dv4uqavtZaD1wgEezg0urR3SD0gatFRMb_g/viewform?usp=sf_link', class: "link link-primary dark:link-secondary" %>よりご連絡ください。</p>
    </div>

    <div class="flex">
      <p class="text-xs md:text-sm text-gray-700 dark:text-neutral">2025年2月28日 制定</p>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<div>
  <div class="container mx-auto">
    <div class="flex flex-wrap">
      <div class="w-full lg:w-1/2 lg:mx-auto">
        <div class="flex flex-wrap mt-3 mb-3 px-4">
          <%= link_to map_shops_path, data: { turbo: false }, class: "btn btn-primary hover:bg-custom-hover-brown text-white mr-5 mb-3" do %>
              マップ検索
          <% end %>
          <div class="flex-grow">
            <%= render 'shops/search_form', q: @q, url: shops_path %>
          </div>
        </div>
        <%= image_tag 'toppage.jpg' %>
      </div>
    </div>
  </div>
</div>