config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get "terms_of_use", to: "static_pages#terms_of_use"
  get "privacy_policy", to: "static_pages#privacy_policy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :posts, only: %i[index show edit update destroy] do
  end
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show edit update destroy]
    collection do
      get 'map', to: 'shops#map', as: 'map'
      get :auto_search
    end
    collection do
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]
  resources :likes, only: %i[index create destroy]

  resource :user, only: [:show]

  get 'images/ogp_image.png', to: 'images#ogp', as: 'images_ogp'
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :bookmarks, dependent: :destroy
    def self.ransackable_attributes(auth_object = nil)
        ["name", "address"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["shop"]
    end
    validates :name, :address, presence: true

    # addressカラムを使って緯度・経度を取得
    geocoded_by :address
    # addressが変更されたときに緯度・経度を更新
    after_validation :geocode, if: :address_changed?
    # 位置情報を扱うためのメソッドを追加
    acts_as_mappable default_units: :kms,
                    lat_column_name: :latitude,
                    lng_column_name: :longitude

    # 任意のレビュー項目もあるため`nil` や `0` を除外した投稿で平均値を算出
    def average_score_for(column)
        valid_posts = posts.where.not(column => [nil, 0])
        average = valid_posts.average(column)
        average.present? ? average.round(1) : 0.0
    end

    # 任意のレビュー項目もあるため`nil` や `0` を除外した投稿で平均値をパーセンテージに変換
    def average_score_percentage_for(column)
        valid_posts = posts.where.not(column => [nil, 0])
        if valid_posts.exists?
            (valid_posts.average(column).round(1).to_f * 100 / 5).round(1)
        else
            0.0
        end
    end

    # power_availabilityの各選択肢ごとの割合を計算するメソッド
    def power_availability_percentage_for(column)
        total_posts = posts.count.to_f
        return {} if total_posts.zero?

        percentages = {}
        Post.send(column.to_s.pluralize).keys.each do |key|
        count = posts.where(column => key).count
        percentages[key] = (count / total_posts * 100).round(1)
        end
        percentages
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  before_action :set_google_maps_api_key

  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true)
  end

  def show
    @shop = Shop.find(params[:id])
    @posts = @shop.posts.includes(:user).order(created_at: :desc)
    @average_rating = @shop.average_score_for(:rating)
    @average_quietness_level = @shop.average_score_for(:quietness_level)
    @average_seat_comfort_level = @shop.average_score_for(:seat_comfort_level)
    @average_wifi_comfort_level = @shop.average_score_for(:wifi_comfort_level)
    @power_availability_percentage = @shop.power_availability_percentage_for(:power_availability)
  end

  def map
    # パラメータから緯度・経度を取得
    latitude = params[:latitude].to_f
    longitude = params[:longitude].to_f
    origin = [latitude, longitude]
    # 半径10km以内のカフェを検索
    @shops = Shop.all.within(10, origin: [latitude, longitude])
    # カフェの情報をJavaScriptに渡す
    gon.shops = @shops.as_json
    # リクエストがHTMLかJSONかをチェック
    respond_to do |format|
      format.html # HTMLの場合は通常のビューを表示
      format.json { render json: { shops: @shops.as_json } } # JSON形式の場合はデータを返す
    end
  end

  def bookmarks
    # @bookmark_shops = current_user.bookmark_shops.includes(:user).order(created_at: :desc)
    @bookmark_shops = current_user.bookmark_shops.order(created_at: :desc)
  end

  # オートコンプリート機能
  def auto_search
    @shops = Shop.ransack(name_or_address_cont: params[:q]).result.order(name: :asc)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_google_maps_api_key
    gon.google_maps_api_key = Rails.application.credentials.GOOGLE_MAPS_API_KEY
  end
end

app/views/shops/_bookmark.html.erb
<%= link_to bookmarks_path(shop_id: shop.id), id: "bookmark-button-for-shop-#{shop.id}", data: { turbo_method: :post } do %>
  <i class="fa-regular fa-bookmark hover:text-yellow-500">
    <span class="text-sm text-gray-500 hover:text-yellow-500">保存</span>
  </i>
<% end %>

app/views/shops/_bookmark_buttons.html.erb
<% if current_user.bookmark?(shop) %>
  <%= render 'unbookmark', { shop: shop } %>
<% else %>
  <%= render 'bookmark', { shop: shop } %>
<% end %>

app/views/shops/_search_form.html.erb
<%= search_form_for q, url: url do |f| %>
  <div class="mx-auto flex justify-center w-full max-w-md md:max-w-2xl">

    <div data-controller="autocomplete" data-autocomplete-url-value="/shops/auto_search" role="combobox" class="relative flex-grow w-full pt-1">

      <%= f.search_field :name_or_address_cont, data: { autocomplete_target: 'input' }, class: 'form-input w-full border pl-2 pr-2 py-2 rounded-l-md shadow-sm focus:border-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-200' ,placeholder: '検索ワード' %>
      <input type="hidden" name="shop_id" data-autocomplete-target="hidden"/>
      <%= f.hidden_field :name, data: { autocomplete_target: 'hidden' } %>
      <%# オートコンプリートのリストが表示される %>
      <ul class="w-full max-h-60 overflow-auto absolute border border-gray-300 rounded-md mt-2 bg-white shadow-lg" data-autocomplete-target="results"></ul>

    </div>

    <div class="ml-2">
      <%= f.submit class: 'btn btn-primary text-white font-bold py-2 px-4 rounded-r-md w-full sm:w-auto' %>
    </div>

  </div>
<% end %>

app/views/shops/_shop.html.erb
<div class="sm:w-full lg:w-full">
  <div id="shop-id-<%= shop.id %>" class="p-3">
    <div class="bg-white rounded shadow">
      <ul class="w-full bg-white p-6 rounded-lg shadow-lg">
        <li class="flex items-center justify-between">
          <span class="font-bold text-lg hover:text-yellow-500"><%= link_to "#{shop.name}", shop_path(shop) %></span>
          <span>
            <% if user_signed_in? %>
              <%= render 'bookmark_buttons', { shop: shop } %>
            <% else %>
              <span onclick="document.getElementById('login_modal').showModal(); document.getElementById('login-button').focus();" style="cursor: pointer;">
                <i class="fa-regular fa-bookmark  hover:text-yellow-500"></i>
                <span class="text-sm text-gray-500  hover:text-yellow-500">保存</span>
              </span>
            <% end %>
          </span>
        </li>
        <li class="mt-2 text-sm text-gray-500"><%= shop.address %></li>
      </ul>
    </div>
  </div>
</div>

<%# ログインすると使える機能案内ダイアログ %>
<dialog id="login_modal" class="modal">
    <div class="modal-box">
        <h3 class="text-lg font-bold">
            ログインして続ける
        </h3>
        <p class="py-4">
            <ul>
              <li>ログインすると使える機能</li>
              <li>・レビュー投稿機能</li>
              <li>・お店ブックマーク機能</li>
              <li>・レビューいいね機能</li>
            </ul>
        </p>
        <div class="modal-action">
            <%# 戻るボタン %>
            <%= form_with url: '#', method: :dialog do %>
                <%= button_tag '✕', class: 'btn btn-sm btn-circle btn-ghost absolute right-2 top-2' %>
            <% end %>
            <%# ログインボタン %>
            <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary hover:bg-custom-hover-brown text-white rounded-md" %>
        </div>
    </div>
</dialog>

app/views/shops/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(shop_id: shop.id)), id: "unbookmark-button-for-shop-#{shop.id}", data: { turbo_method: :delete } do %>
  <i class="fa-solid fa-bookmark hover:text-yellow-500">
    <span class="text-sm text-gray-500 hover:text-yellow-500">保存</span>
  </i>
<% end %>

app/views/shops/auto_search.html.erb
<% @shops.each do |shop| %>
    <li class="flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-blue-200 focus:ring-2 focus:ring-gray-200 bg-white " role="option" data-autocomplete-value="<%= shop.id %>" data-autocomplete-label="<%= shop.name %>">
        <%= shop.name %>
    </li>
<% end %>

app/views/shops/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="w-full max-w-4xl mx-auto pt-3">
  <div class="text-center m-6">
    <h2><%= t('.title') %></h2>
  </div>
  <div class="flex flex-wrap justify-center mb-3">
    <div class="w-full max-w-3xl">
      <% if user_signed_in? %>
        <% if @bookmark_shops.present? %>
          <% @bookmark_shops.each do |bookmark_shop| %>
            <%= render 'shops/shop', shop: bookmark_shop %>
          <% end %>
        <% else %>
          <p><%= t('.no_bookmarks') %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="w-full max-w-4xl mx-auto pt-3">
  <div class="flex flex-wrap justify-center">
    <div class="sm:w-full p-3">
      <!-- 検索フォーム -->
      <%= render 'search_form', q: @q, url: shops_path %>
    </div>
  </div>
  <div class="flex flex-wrap justify-center mb-3">
    <% if @shops.present? %>
      <div class="w-full m-3 px-3 max-w-3xl">
        <%= "検索結果:#{@shops.size}件" %>
      </div>
      <div class="w-full max-w-3xl">
        <%= render @shops %>
      </div>
    <% else %>
      <div class="mb-3 text-center">検索結果:0件</div>
    <% end %>
  </div>
</div>

app/views/shops/map.html.erb
<div>
  <div class="container mx-auto">
    <div class="flex flex-wrap">
      <!-- 大きい画面で横並びにするためにflex-rowを追加 -->
      <div class="w-full lg:mx-auto lg:flex lg:flex-row max-w-screen-xl lg:my-6">
        <!-- ショップリスト部分 -->
        <div class="w-full lg:w-2/5 lg:ml-6 mr-3">
          <div class="flex hidden md:block">
            <button onclick="updateSearch()" class="btn btn-primary hover:bg-custom-hover-brown text-white mb-3">
                現在地で検索
            </button>
          </div>
          <div class="hidden md:block number-of-shops"></div> <!-- 件数を表示するための要素 -->
          <div class="hidden md:block w-full overflow-y-auto mt-3 h-[calc(100vh-300px)]">
              <ul class="shop-list"></ul> <!-- ショップリストを表示するための要素 -->
          </div>
        </div>
        <!-- マップ部分 -->
        <div id="map" class="h-[calc(100vh-200px)] m-3 lg:w-3/5"></div>
        <div class="md:hidden mx-auto flex justify-center my-2">
          <!-- 現在地で検索ボタン -->
          <button onclick="updateSearch()" class="btn btn-primary hover:bg-custom-hover-brown text-white p-2 text-sm">
            現在地で検索
          </button>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  let map
  let currentLocationMarker;
  let defaultLocation = { lat: 35.68978920591743, lng: 139.70055989948156 };
  let lat = defaultLocation.lat;
  let lng = defaultLocation.lng;
  let marker, markers = [];
  let shops = gon.shops;
  let currentInfoWindow = null;

  window.addEventListener("DOMContentLoaded", function() {
    if (!window.google || !window.google.maps) {
      loadMapScript(); // スクリプトをロード
    } else if (typeof map === 'undefined') {
      // マップが初期化されていなければ初期化
      initMap();
    }
  });

  // Maps JavaScript APIを非同期で読み込む
  function loadMapScript() {
      var script = document.createElement('script');
      script.src = `https://maps.googleapis.com/maps/api/js?key=${gon.google_maps_api_key}&callback=initMap`;
      script.async = true;
      script.defer = true;
      document.head.appendChild(script);
  }

  // GoogleMap初期化
  function initMap() {
    const geocoder = new google.maps.Geocoder();
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 12,
      streetViewControl: false, // ストリートビューのボタン非表示
      mapTypeControl: false, // 地図、航空写真のボタン非表示
      fullscreenControl: false, // フルスクリーンボタン非表示

    });

    // 現在地を取得
    showCurrentLocation();

    // 現在地をマーカーで表示
    addCurrentLocationMaker();

    // 現在地近辺のshopを検索・取得
    updateSearch();
  }

  // 現在地を取得
  function showCurrentLocation(){
    // 非同期処理のままだと、位置情報が取得される前に次の処理（現在地周辺のカフェの検索・取得）が実行されてしまうためPromiseを使って非同期処理の結果に応じて次の処理を実行するようにする
    return new Promise((resolve, reject) => {
      if (navigator.geolocation) {
        // ブラウザが位置情報の取得をサポートしている場合
        // 現在地を取得
        navigator.geolocation.getCurrentPosition(
          (position) => {
            const pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude,
            };

            if (map) {
              // マップの中心を設定
              map.setCenter(pos);
              currentLocationMarker.setPosition(pos);
              resolve(pos);  // 成功時に位置を返す
            } else {
              console.error("map is not initialized.");
              reject();
            }
          },
          () => {
            // 位置情報の取得に失敗した場合
            alert('位置情報の取得に失敗しました。');
            if (map) {
              // マップの中心をデフォルト位置に設定
              map.setCenter(defaultLocation);
              currentLocationMarker.setPosition(defaultLocation);
              resolve(defaultLocation);  // 失敗時はデフォルト位置を返す
            } else {
              console.error("map is not initialized.");
              reject();
            }
          }
        );
      } else {
        alert('お使いのブラウザでは位置情報の取得がサポートされていません。');
        if (map) {
          // サポートされていない場合もデフォルト位置に設定
          map.setCenter(defaultLocation);
          resolve(defaultLocation);
        } else {
          console.error("map is not initialized.");
          reject();
        }
      }
    });
  }

  // 現在地をマーカーで表示
  function addCurrentLocationMaker() {

    // 現在地の位置が変わると複数のマーカが表示されてしまうため、マーカーが存在する場合は削除
    if (currentLocationMarker) {
      currentLocationMarker.setMap(null);
    }

    currentLocationMarker = new google.maps.Marker({
      map: map,
      position: map.getCenter(), // 初期位置をマップの中心に設定
      title: "現在地",
      zIndex: 9999 // カフェのマーカーと重なったときに現在地のマーカーが一番前面に表示するように設定
    });
  }


  // 現在地近辺のshopを検索・取得
  function updateSearch(){

    // 現在地を取得
    showCurrentLocation().then((pos) => {
    var centerLatLng = {
      latitude: pos.lat,
      longitude: pos.lng
    };

    // 現在地のマーカーを追加
    addCurrentLocationMaker();

    // 現在地近辺のshopデータを検索・取得
    fetch(`/shops/map.json?latitude=${centerLatLng.latitude}&longitude=${centerLatLng.longitude}`)
      .then(response => response.json())
      .then(data => {
        console.log(data); // デバッグ用にデータを出力
        clearShopMarkers(); // 既存のshopマーカーを削除
        addShopMarkers(data.shops); // 取得したデータでshopマーカーを追加
        updateNumberOfShops(data.shops); // 取得したデータで件数を更新
        updateShopList(data.shops); // 取得したデータでshopリストを更新
      })
      .catch(error => console.error('Error:', error));
    });
  }

  // shopマーカーを削除
  function clearShopMarkers() {
    markers.forEach(marker => {
      marker.setMap(null);
    });
    markers = [];
  }

  // shopマーカーを追加
  function addShopMarkers(data) {
    data.forEach(shop => {
      const marker = new google.maps.Marker({
        position: { lat: parseFloat(shop.latitude), lng: parseFloat(shop.longitude) },
        map: map,
        title: shop.name,
        icon: {
          url: "https://maps.google.com/mapfiles/ms/micons/orange-dot.png",
          scaledSize: new google.maps.Size(30, 30) //サイズ
        }
      });

      // マーカーとリストのクリックイベントを紐づけられるようにマーカーにshop.idを付与
      marker.shopId = shop.id;

      // GoogleMapsAPIが複数回読み込まれることによるマップの不具合を回避するためTurboを無効化
      const infoWindow = new google.maps.InfoWindow({
        content: `
          <div class="m-2">
            <a href="/shops/${shop.id}"
              data-turbo="false"
              class="link link-primary font-semibold outline-none focus:outline-none">
              ${shop.name}
            </a>
          </div>
        `
      });

      marker.addListener("click", () => {

        // 他のマーカーを選択するとInfoWindowが増えてしまうため閉じる処理を追加
        if (currentInfoWindow) {
          currentInfoWindow.close();
        }
        infoWindow.open({
          anchor: marker,
          map,
        });
        // 現在のInfoWindowを更新
        currentInfoWindow = infoWindow;
        // リストの該当店舗をハイライト
        highlightShopInList(shop.id);
      });

      markers.push(marker);

    });
  }

    // リストの該当店舗をハイライト
  function highlightShopInList(shopId) {

    const shopElements = document.querySelectorAll('.shop-item');

    shopElements.forEach(el => {
      el.classList.remove('bg-custom-light-gray'); // 既存のハイライト削除
      if (el.dataset.shopId == shopId) {
        el.classList.add('bg-custom-light-gray'); // 該当店舗にハイライト
        el.scrollIntoView({ behavior: "smooth", block: "center" }); // スクロール
      }
    });
  }

  // リストのクリックイベントをセット
  function setupShopListEvents() {
    document.querySelectorAll('.shop-item').forEach(el => {
      el.addEventListener('click', () => {
        const shopId = el.dataset.shopId;
        const marker = markers.find(m => m.shopId == shopId);
        if (marker) {
          new google.maps.event.trigger(marker, "click"); // マーカーをクリックしたことにする
        }
      });
    });
  }

  // innerHTMLを使って検索結果に応じて件数の表示を動的に更新
  function updateNumberOfShops(shops) {
    const numberOfShopsElement = document.querySelector('.number-of-shops');
    if (!numberOfShopsElement) {
      console.error("Number of shops element not found.");
      return;
    }
    numberOfShopsElement.textContent = `半径10km以内の検索結果: ${shops.length}件`;
  }

  // innerHTMLを使って取得したshopデータに応じてshopリストの表示を動的に更新
  function updateShopList(shops) {
    const shopListElement = document.querySelector('.shop-list');
    if (!shopListElement) {
      console.error("Shop list element not found.");
      return;
    }

    shopListElement.innerHTML = '';
    shops.forEach(shop => {
      const shopElement = document.createElement('li');

      // GoogleMapsAPIが複数回読み込まれることによるマップの不具合を回避するためTurboを無効化
      shopElement.innerHTML = `
          <div class="shop-item w-full h-full flex-none" data-shop-id="${shop.id}">
            <div id="shop-id-${shop.id}" class="p-2 sm:w-full snap-start snap-center"  data-shop-id="${shop.id}">
              <div class="bg-white rounded shadow">
                <ul class="w-full bg-white p-3 rounded-lg shadow-lg hover:bg-gray-50 text-sm md:text-lg">
                  <li class="flex items-center space-x-2 font-bold">
                    <a href="/shops/${shop.id}" data-turbo="false"  class="link link-primary">${shop.name}</a>
                  </li>
                  <li class="hidden md:block mt-2 text-gray-500 text-sm">${shop.address}</li>
                </ul>
              </div>
            </div>
          </div>
        `;
      shopListElement.appendChild(shopElement);
    });
    // リストのクリックイベントをセット
    setupShopListEvents();
  }

  window.initMap = initMap;

  window.showCurrentLocation = showCurrentLocation;

</script>