config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get "terms_of_use", to: "static_pages#terms_of_use"
  get "privacy_policy", to: "static_pages#privacy_policy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :posts, only: %i[index show edit update destroy] do
  end
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show edit update destroy]
    collection do
      get 'map', to: 'shops#map', as: 'map'
      get :auto_search
    end
    collection do
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]
  resources :likes, only: %i[index create destroy]

  resource :user, only: [:show]

  get 'images/ogp_image.png', to: 'images#ogp', as: 'images_ogp'
end

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='bg-custom-light-gray'>
  <div class='px-6 py-4 w-full'>
    <div class='flex flex-wrap justify-center'>
      <div class='w-full'>
        <div class='text-center'>
          <p class='text-sm'>
            <span class='mr-4'><%= link_to "利用規約", terms_of_use_path %></span>
            <span class='mr-4'><%= link_to "プライバシーポリシー", privacy_policy_path %></span>
            <span><%= link_to 'お問い合わせ', 'https://docs.google.com/forms/d/e/1FAIpQLScEoalxTjFE971Dv4uqavtZaD1wgEezg0urR3SD0gatFRMb_g/viewform?usp=sf_link', target: "_blank", rel: "noopener noreferrer" %></span>
          </p>
          <p class='text-sm text-gray-600'>© 2025 Learn&Latte. Copyright All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="flex items-center justify-between bg-custom-light-gray h-16">
    <%= link_to '/', class: 'ml-5 text-2xl font-bold' do %>
      Learn&Latte
    <% end %>
    <div class="flex items-center">
      <ul class="flex items-center space-x-5 mr-5">
        <% if user_signed_in? %>
          <div class="flex-none">
            <ul class="menu menu-horizontal flex items-center text-black">
              <li>
                <details class="relative">
                  <summary>メニュー</summary>
                  <ul class="bg-my_white px-1 py-2 rounded-md top-7 right-1 leading-normal w-48 z-50">
                    <li><%= link_to t('header.mypage'), user_path %></li>
                    <li><%= link_to t('header.bookmark_index'), bookmarks_shops_path %></li>
                    <li><%= link_to t('header.logout'), destroy_user_session_path, data: { turbo_method: :delete } %></li>
                  </ul>
                </details>
              </li>
            </ul>
          </div>
        <% else %>
          <li>
            <%= link_to t('header.create_account'), new_user_registration_path %>
          </li>
          <li>
            <%= link_to t('header.login'), new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_rating.html.erb
<div class="rating">
  <% (1..5).each do |star| %>
    <i class="fa-solid fa-star <%= 'text-yellow-500' if star <= rating %> <%= 'text-gray-300' if star > rating %>"></i>
  <% end %>
</div>