config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#top"

  get "terms_of_use", to: "static_pages#terms_of_use"
  get "privacy_policy", to: "static_pages#privacy_policy"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :posts, only: %i[index show edit update destroy] do
  end
  resources :shops, only: %i[index show] do
    resources :posts, only: %i[new create show edit update destroy]
    collection do
      get 'map', to: 'shops#map', as: 'map'
      get :auto_search
    end
    collection do
      get :bookmarks
    end
  end

  resources :bookmarks, only: %i[create destroy]
  resources :likes, only: %i[index create destroy]

  resource :user, only: [:show]

  get 'images/ogp_image.png', to: 'images#ogp', as: 'images_ogp'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  has_many :likes, dependent: :destroy
  mount_uploaders :post_images, PostImageUploader

  ## validates
  validates :rating, presence: true

  ## enum
  enum power_availability: {
    電源が使える席があって使えた: 1,
    電源が使える席がなくて使えなかった: 2,
    特に電源を使う必要がなかった: 3
  }

  def self.ransackable_attributes(auth_object = nil)
    [
      "body", "created_at", "id", "ratign", "power_availability",
      "quietness_level", "seat_comfort_level", "shop_id", "title",
      "updated_at", "user_id", "wifi_comfort_level"
    ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["shop", "user"]
  end

  ## 画像削除を処理するメソッド
  def remove_image_at_index(index)
    remain_images = self.post_images.dup
    remain_images.delete_at(index)
    self.post_images = remain_images
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # 指定のアクションに対して認証を要求
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_shop, only: [:new, :create, :edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc)
  end

  def new
    # 初期値として3を設定
    @post = Post.new(rating: 3, quietness_level: 3, seat_comfort_level: 3, wifi_comfort_level: 3)
  end

  def create
    @post = current_user.posts.build(post_params.merge(shop_id: @shop.id))
    if @post.save
      redirect_to shop_path(@shop), success: t('posts.create.success')
    else
      # 保存に失敗した場合の処理
      flash.now[:danger] = t('posts.create.failure') + @post.errors.full_messages.join(', ')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
    # 前ページセッションを保存
    session[:previous_url] = request.referer
    # 画像キャッシュ
    @post.post_images.each { |image| image.cache! } unless
    @post.post_images.blank?
  end

  def update

    @post = current_user.posts.find(params[:id])

    # 現在の投稿に関連付けられている画像をexisting_imagesに保持
    existing_images = @post.post_images

    # post_paramsからshop_idとpost_imagesを除いた属性を@postに割り当て
    @post.assign_attributes(post_params.except(:shop_id, :post_images))

    # 新しい画像が送信されている場合、既存の画像に追加
    if post_params[:post_images].present?
      @post.post_images += post_params[:post_images]
    else
      # 画像が送信されていない場合は元の画像を保持
      @post.post_images = existing_images
    end

    # 画像削除処理
    if params[:post][:remove_image_at].present?
      # 削除対象のインデックスをカンマ区切りで取得し、削除処理を行う
      params[:post][:remove_image_at].split(',').each do |index|
        index = index.to_i
        # インデックスが画像の数より小さい場合のみ削除処理を行う
        @post.remove_image_at_index(index) if index < @post.post_images.length
      end
    end

    # 更新処理
    if @post.save
      # flash[:success] = t('posts.update.success') # フラッシュメッセージ
      redirect_to session[:previous_url] || shop_post_path(@shop, @post), success: t('defaults.flash_message.updated', item: @post.model_name.human) # 前のページにリダイレクト
    else
      flash.now[:danger] = t('posts.update.failure') + @post.errors.full_messages.join(', ')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    # redirect_to posts_path, success: t('defaults.flash_message.deleted', item: post.model_name.human), status: :see_other
    # TODO: 下記を使った形式に変更する。
    # item: post.model_name.human
    redirect_to shop_posts_path, success: t('defaults.flash_message.deleted'), status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :rating, :quietness_level, :seat_comfort_level, :wifi_comfort_level, :power_availability, :body, { post_images: [] }, :post_images_cache)
  end

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

end

app/views/posts/_form.html.erb
<%= form_with model: [@shop, @post], class: "new_post" do |f| %>

  <!-- タイトル -->
  <div class="mb-3">
    <%= f.label :タイトル, class: "block font-bold mb-2" %>
    <%= f.text_field :title, class: "focus:border-gray-500 focus:outline-none focus:ring focus:ring-gray-200 form-input w-full border pl-2 pr-2 p-2" %>
  </div>

  <!-- 評価 TODO: 評価は星でも入力できるようにする -->
  <!-- 評価 -->
  <div class="mb-3">
    <%= f.label :評価, class: "block font-bold mb-2" %>
    <div class="rating">
      <%= f.radio_button :rating, 1, class: "mask mask-star bg-primary", id: "rating-star-1", checked: f.object.rating == 1 %>
      <%= f.radio_button :rating, 2, class: "mask mask-star bg-primary", id: "rating-star-2", checked: f.object.rating == 2 %>
      <%= f.radio_button :rating, 3, class: "mask mask-star bg-primary", id: "rating-star-3", checked: f.object.rating == 3 %>
      <%= f.radio_button :rating, 4, class: "mask mask-star bg-primary", id: "rating-star-4", checked: f.object.rating == 4 %>
      <%= f.radio_button :rating, 5, class: "mask mask-star bg-primary", id: "rating-star-5", checked: f.object.rating == 5 %>
    </div>
  </div>

  <!-- お店の雰囲気 -->
  <div class="mb-3">
    <%= f.label :お店の雰囲気（数字が小さい方が賑やか、大きい方が静か）, class: "block font-bold mb-2" %>
    <div class="rating">
      <%= f.radio_button :quietness_level, 1, class: "mask mask-star bg-primary", id: "quietness-star-1", checked: f.object.quietness_level == 1 %>
      <%= f.radio_button :quietness_level, 2, class: "mask mask-star bg-primary", id: "quietness-star-2", checked: f.object.quietness_level == 2 %>
      <%= f.radio_button :quietness_level, 3, class: "mask mask-star bg-primary", id: "quietness-star-3", checked: f.object.quietness_level == 3 %>
      <%= f.radio_button :quietness_level, 4, class: "mask mask-star bg-primary", id: "quietness-star-4", checked: f.object.quietness_level == 4 %>
      <%= f.radio_button :quietness_level, 5, class: "mask mask-star bg-primary", id: "quietness-star-5", checked: f.object.quietness_level == 5 %>
    </div>
  </div>

  <!-- 座席 -->
  <div class="mb-3">
    <%= f.label :座席の快適さ（勉強しやすい机・椅子であったか）, class: "block font-bold mb-2" %>

    <div class="rating">
      <%= f.radio_button :seat_comfort_level, 1, class: "mask mask-star bg-primary", id: "rating-star-1", checked: f.object.seat_comfort_level == 1 %>
      <%= f.radio_button :seat_comfort_level, 2, class: "mask mask-star bg-primary", id: "rating-star-2", checked: f.object.seat_comfort_level == 2 %>
      <%= f.radio_button :seat_comfort_level, 3, class: "mask mask-star bg-primary", id: "rating-star-3", checked: f.object.seat_comfort_level == 3 %>
      <%= f.radio_button :seat_comfort_level, 4, class: "mask mask-star bg-primary", id: "rating-star-4", checked: f.object.seat_comfort_level == 4 %>
      <%= f.radio_button :seat_comfort_level, 5, class: "mask mask-star bg-primary", id: "rating-star-5", checked: f.object.seat_comfort_level == 5 %>
    </div>
  </div>

  <!-- Wi-Fi -->
  <div class="mb-3">
    <%= f.label :"Wi-Fiの快適さ", class: "block font-bold mb-2" %>
    <div class="rating">
      <%= f.radio_button :wifi_comfort_level, 1, class: "mask mask-star bg-primary", id: "quietness-star-1", checked: f.object.wifi_comfort_level == 1 %>
      <%= f.radio_button :wifi_comfort_level, 2, class: "mask mask-star bg-primary", id: "quietness-star-2", checked: f.object.wifi_comfort_level == 2 %>
      <%= f.radio_button :wifi_comfort_level, 3, class: "mask mask-star bg-primary", id: "quietness-star-3", checked: f.object.wifi_comfort_level == 3 %>
      <%= f.radio_button :wifi_comfort_level, 4, class: "mask mask-star bg-primary", id: "quietness-star-4", checked: f.object.wifi_comfort_level == 4 %>
      <%= f.radio_button :wifi_comfort_level, 5, class: "mask mask-star bg-primary", id: "quietness-star-5", checked: f.object.wifi_comfort_level == 5 %>
    </div>
  </div>

  <!-- 電源 -->
  <div class="mb-3">
  <%= f.label :"電源は使えたか", class: "block font-bold mb-2" %>
    <%= f.select :power_availability, Post.power_availabilities.keys.map { |k| [Post.human_attribute_name("power_availability.#{k}"), k] }, { include_blank: "選択して下さい" }, { class: "border bg-gray-200 p-3" } %>
  </div>

  <!-- 本文 -->
  <div class="mb-3">
    <%= f.label :本文, class: "block font-bold mb-2" %>
    <%= f.text_area :body, class: "focus:border-gray-500 focus:outline-none focus:ring focus:ring-gray-200 form-input w-full border p-3", rows: "10" %>
  </div>

  <!-- 画像 -->
  <div class="mb-3">
    <%= f.label :画像アップロード, class: "block font-bold mb-2" %>
    <%= f.file_field :post_images, multiple: true, class: "form-control js-file-select-preview", accept: 'image/*' %>
    <%= f.hidden_field :post_images_cache %>

    <!-- 削除された画像インデックスを保持する隠しフィールド -->
    <%= f.hidden_field :remove_image_at, id: 'remove_image_input', value: "" %>

    <% if @post.post_images.present? %>
      <div id="preview-container" class="mt-3" style="display: flex; flex-wrap: wrap; gap: 10px;">

        <% @post.post_images.each_with_index do |image, index| %>

          <div id="image-<%= index %>">
            <!-- TODO:モーダルで画像表示に変更 -->
            <%= link_to image.url, target: "_blank", rel: "noopener" do %>
              <%= image_tag image.thumb.url, class: "object-cover rounded-t cursor-pointer" %>
            <% end %>
            <button type="button" class="remove-image-btn" data-index="<%= index %>" data-review-id="<%= @post.id %>">
              <i class="fa-solid fa-trash"></i>
            </button>
          </div>
        <% end %>

      </div>
    <% else %>
      <div id="preview-container" class="mt-3" style="display: flex; flex-wrap: wrap; gap: 10px;">jpg,jpeg,gif,png形式の画像が選択できます</div>
    <% end %>
  </div>

  <%= f.submit nil, class: "btn btn-primary hover:bg-custom-hover-brown text-white font-bold py-2 px-4 rounded mb-4" %>
<% end %>

<script>
    // 画像削除ボタン
    document.addEventListener('click', function (event) {
      const target = event.target.closest('.remove-image-btn');

      if (target) {

        event.preventDefault(); // デフォルトの動作を無効化
        event.stopPropagation(); // イベントのバブリングを停止

        const index = target.dataset.index;
        const removeImageInput = document.getElementById('remove_image_input');


        // 既に削除対象が選択されている場合は何もせずに終了
        if (removeImageInput.value.includes(index)) {
          return; // すでに削除された画像なら処理を終了
        }

        if (!removeImageInput) {
          console.error('remove_image_input が見つかりません');
          return;
        }

        // 確認のダイアログを表示
        const confirmed = confirm('この画像を削除してもよろしいですか？');
        if (!confirmed) {
          return;
        }

        // 削除する画像のインデックスをインプットに追加
        const currentValue = removeImageInput.value;
        removeImageInput.value = currentValue ? `${currentValue},${index}` : index;

        // 画像をフォームから削除（画面上からは見えなくする）
        const imageElement = document.getElementById(`image-${index}`);
        if (imageElement) {
          imageElement.style.display = 'none';
        }
      }
    });

</script>

app/views/posts/_like.html.erb
<%= link_to likes_path(post_id: post.id), id: "like-button-for-post-#{post.id}", data: { turbo_method: :post }, method: :post do %>
  <i class="fa-regular fa-heart hover:text-yellow-500">
    <span class="text-sm text-gray-500 hover:text-yellow-500">いいね</span>
  </i>
<% end %>

app/views/posts/_like_buttons.html.erb
<% if current_user.like?(post) %>
    <%= render 'posts/unlike', { post: post } %>
<% else %>
    <%= render 'posts/like', { post: post } %>
<% end %>

app/views/posts/_post.html.erb
<div class="sm:w-full lg:w-full mb-3">
  <div id="post-id-<%= post.id %>" class="p-3">
    <div class="bg-white rounded shadow">
      <div class="p-6">
        <div class="flex items-center">
          <ul class="list-none">
            <li class="flex space-x-2 mb-3"><h4 class="text-left font-bold flex-grow text-2xl hover:text-yellow-500"><%= link_to "#{post.shop.name}", shop_path(post.shop) %></h4></li>
            <li class="flex items-center">
              <ul class="flex space-x-2">
                <li><%= "#{post.user.name}" %></li>
                <li><%= l post.created_at.to_date, format: :long %></li>
              </ul>
            </li>
          </ul>
        </div>

        <div class="border-t my-3"></div>
        <ul class="list-none mt-2 space-y-2 hover:text-yellow-500">
          <%= link_to post_path(post) do %>
            <li class="flex items-center space-x-2 font-bold"><%= "#{post.title}" %></li>
            <li class="flex items-center space-x-2"><%= "評価 : #{post.rating}" %>
              <%= render 'shared/rating', rating: post.rating %>
            </li>
            <li class="flex items-center space-x-2"><%= "お店の雰囲気 : #{post.quietness_level}" %>
              <%= render 'shared/rating', rating: post.quietness_level %>
            </li>
            <li class="flex items-center space-x-2"><%= "座席の快適さ : #{post.seat_comfort_level}" %>
              <%= render 'shared/rating', rating: post.seat_comfort_level %>
            </li>
            <li class="flex items-center space-x-2"><%= "Wi-fiの快適さ : #{post.wifi_comfort_level}" %>
              <%= render 'shared/rating', rating: post.wifi_comfort_level %>
            </li>
            <li class="flex items-center space-x-2"><%= "電源は使えたか : #{post.power_availability}" %></li>
            <li class="flex items-center space-x-2 mt-2"><%= simple_format(post.body) %></li>
            <% if post.post_images.present? %>
              <div class="mt-3  flex flex-wrap gap-2">
                <!-- TODO:モーダルで画像表示に変更 -->
                <% post.post_images.each do |image| %>
                  <%= link_to image.url, target: "_blank", rel: "noopener" do %>
                    <%= image_tag image.thumb.url, width: "100", height: "100", class: "object-cover rounded-t cursor-pointer" %>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </ul>
        <div class="flex justify-end mr-3">
          <% if user_signed_in? %>
            <%= render 'posts/like_buttons', { post: post } %>
          <% else %>
            <div class="flex items-center">
              <i class="fa-regular fa-heart hover:text-yellow-500"></i>
              <span class="text-sm text-gray-500 hover:text-yellow-500">いいね</span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for q, url: url do |f| %>
  <div class="flex mb-3">
    <%= f.search_field :title_or_body_or_shop_name_cont, class: 'form-input flex-grow border pl-3 pr-3', placeholder: '検索ワード' %>
    <div class="input-group-append ml-3">
      <%= f.submit class: 'btn btn-primary hover:bg-custom-hover-brown hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
    </div>
  </div>
<% end %>

app/views/posts/_unlike.html.erb
<%= link_to like_path(current_user.likes.find_by(post_id: post.id)), id: "unlike-button-for-post-#{post.id}", data: { turbo_method: :delete }, method: :delete do %>
  <i class="fa-solid fa-heart hover:text-yellow-500">
    <span class="text-sm text-gray-500 hover:text-yellow-500">いいね</span>
  </i>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>

<div class="container mx-auto px-4">
  <div class="flex flex-wrap -mx-4 wrap-vertical-alignment">
    <div class="w-full lg:w-1/2 lg:mx-auto">
      <h1 class="text-2xl font-bold mt-4 mb-4 text-center"><%= t('header.posts.edit.title') %></h1>
      <h1 class="text-2xl font-bold mt-4 mb-4"><%= @shop.name %></h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div>
  <div class="container pt-3 lg:mx-auto">
    <div class="flex flex-wrap justify-center">
      <div class="sm:w-full lg:w-1/3 p-3">
        <!-- 検索フォーム -->
        <%= render 'search_form', q: @q, url: posts_path %>
      </div>
    </div>
    <div class="w-full">
      <!-- レビュー投稿一覧 -->
      <div class="text-2xl font-bold p-3">検索結果</div>
    </div>
    <div class="flex flex-wrap lg:w-1/3">
      <% if @posts.present? %>
        <%= render @posts %>
      <% else %>
        <div class="mb-3">投稿がありません</div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mx-auto px-4">
  <div class="flex flex-wrap -mx-4 wrap-vertical-alignment">
    <div class="w-full lg:w-1/2 lg:mx-auto">
      <h1 class="text-2xl font-bold mt-4 mb-4 text-center"><%= t('header.posts.create.title') %></h1>
      <h1 class="text-2xl font-bold mt-4 mb-4"><%= @shop.name %></h1>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mx-auto p-3">
  <div class="flex flex-wrap">
    <div class="w-full lg:w-1/2 lg:mx-auto">

      <div class="flex items-center justify-between">
        <span class="flex-1 text-2xl font-bold my-5 hover:text-yellow-500 ">
          <%= link_to "#{@post.shop.name}", shop_path(@post.shop) %>
        </span>
      </div>
      <div class="border-t mb-5"></div>

      <article class="card border">
        <div class="card-body">
          <div class="flex flex-wrap wrap-vertical-alignment">
            <div class="w-full">
              <ul class="list-none mb-4 space-y-2">
                <li class="flex items-center">
                  <ul class="flex space-x-2">
                    <li><%= "#{@post.user.name}" %></li>
                    <li><%= l @post.created_at.to_date, format: :long %></li>
                  </ul>
                </li>
                <div class="border-t"></div>
                <li class="flex items-center "><strong><%= @post.title %></strong></li>
                <li class="flex items-center"><%= simple_format(@post.body) %></li>
                <li class="flex items-center"><%= "評価 : #{@post.rating}" %>
                  <%= render 'shared/rating', rating: @post.rating %>
                </li>
                <li class="flex items-center"><%= "お店の雰囲気 : #{@post.quietness_level}" %>
                  <%= render 'shared/rating', rating: @post.quietness_level %>
                </li>
                <li class="flex items-center"><%= "座席の快適さ : #{@post.seat_comfort_level}" %>
                  <%= render 'shared/rating', rating: @post.seat_comfort_level %>
                </li>
                <li class="flex items-center"><%= "Wi-fiの快適さ : #{@post.wifi_comfort_level}" %>
                  <%= render 'shared/rating', rating: @post.wifi_comfort_level %>
                </li>
                <li class="flex items-center"><%= "電源は使えたか : #{@post.power_availability}" %></li>
              </ul>
            </div>

            <div class="flex justify-end w-full m-2 items-center">
              <div class="w-full flex flex-wrap gap-2">
                <% @post.post_images.each do |image| %>
                  <!-- TODO:モーダルで画像表示に変更 -->
                  <%= link_to image.url, target: "_blank", rel: "noopener" do %>
                    <%= image_tag image.thumb.url, class: "object-cover rounded-t cursor-pointer" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>


          <div class="flex justify-end">
            <% prepare_meta_tags @post %>
              <%
                twitter_share_text = "【Learn&Latte〜勉強しやすいカフェ、すぐ探せる！〜】\n\n「#{@post.shop.name}」のレビューをシェア！\n\n#LearnAndLatte ##{@post.shop.name}"
                twitter_share_url = "https://twitter.com/share?" + URI.encode_www_form(
                  url: post_url(@post),
                  text: twitter_share_text
                )
              %>
              <%= link_to twitter_share_url, target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do %>
                <i class="fa-brands fa-square-x-twitter fa-xl hover:text-yellow-500 mr-3">
                  <span class="text-sm text-gray-500 hover:text-yellow-500">シェア</span>
                </i>
            <% end %>
            <% if user_signed_in? %>
              <div><%= render 'like_buttons', { post: @post } %></div>
            <% else %>
              <%# ログインすると使える機能案内ダイアログ %>
              <div onclick="document.getElementById('login_modal').showModal(); document.getElementById('login-button').focus();" style="cursor: pointer;">
                <i class="fa-regular fa-heart hover:text-yellow-500">
                  <span class="text-sm text-gray-500 hover:text-yellow-500">いいね</span>
                </i>
              </div>
            <% end %>
          </div>

          <div class="flex justify-end">
            <ul class="flex justify-start items-center w-full">
              <% if user_signed_in? && current_user.own?(@post) %>
                <div class='ms-auto mt-3'>
                  <%= link_to edit_post_path(@post), id: "button-edit-#{@post.id}" do %>
                    <i class="fa-solid fa-pen-to-square hover:text-yellow-500 mr-3">
                      <span class="text-sm text-gray-500 hover:text-yellow-500">編集</span>
                    </i>
                  <% end %>
                  <%= link_to post_path(@post), id: "button-delete-#{@post.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                    <i class="fa-solid fa-trash hover:text-yellow-500">
                      <span class="text-sm text-gray-500">削除</span>
                    </i>
                  <% end %>
                </div>
              <% end %>
            </ul>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>

<%# ログインすると使える機能案内ダイアログ %>
<dialog id="login_modal" class="modal">
    <div class="modal-box">
        <h3 class="text-lg font-bold">
            ログインして続ける
        </h3>
        <p class="py-4">
            <ul>
              <li>ログインすると使える機能</li>
              <li>・レビュー投稿機能</li>
              <li>・お店ブックマーク機能</li>
              <li>・レビューいいね機能</li>
            </ul>
        </p>
        <div class="modal-action">
            <%# 戻るボタン %>
            <%= form_with url: '#', method: :dialog do %>
                <%= button_tag '✕', class: 'btn btn-sm btn-circle btn-ghost absolute right-2 top-2' %>
            <% end %>
            <%# ログインボタン %>
            <%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary hover:bg-custom-hover-brown text-white rounded-md" %>
        </div>
    </div>
</dialog>